### ISSUE TITLE
Problème d'appel à la méthode getFormules du composant com_booking

### ISSUE THREAD

**Issue by aurelcarlier** [Raphael-johanne/speleo#11]
https://github.com/Raphael-johanne/speleo/blob/578db4009db15c6480e06129abcb217894e6a055/modules/mod_mapping/mod_mapping.php#L13

Cette instruction permet de construire la variable $formules qui doit contenir les formules.
Il faut trouver un moyen de contruire cette variable à partir de la méthode getFormules() déjà définie dans le composant com_booking.

2 pistes possibles :
- via require puis appel de la méthode > ne marche pas (pb d'instanciation / référence classe mère)
- via [cette méthode](https://joomla.stackexchange.com/questions/17101/how-to-call-a-model-method-from-a-system-plugin) qui marche pour d'autres composants mais pas com_booking

**Comment by Raphael-johanne** [comment]
Pourquoi tu l'as closed ?
