### ISSUE TITLE
PB intégration COM_BOOKING

### ISSUE THREAD

**Issue by aurelcarlier** [Raphael-johanne/speleo#6]
Impossible d'accéder depuis le BO à l'affichage des formules via un nouveau menu. Il manque peut être le fichier XML de description du composant (placé à la racine du composant) :
https://docs.joomla.org/J3.x:Developing_an_MVC_Component/Adding_language_management/fr

Edit : le fichier est présent ici : administrator/components/com_booking/booking.xml

**Comment by Raphael-johanne** [comment]
Nop, il faut réinstaller le composant
